### ISSUE TITLE
In Sketch 3.7.1 Relabeling no longer works Correctly

### ISSUE THREAD

**Issue by davidvb** [kenmoore/sketch-relabel-button#11] opened 2016-04-21 10:11 UTC
This shows how much I got to rely on this great plugin.. 
Anyways, In Sketch 3.7.1 Relabeling no longer works correctly. It still changes things but incorrectly.

See an example (a regular folder with 2 layers):
![relabel_broke_-_oh_noes](https://cloud.githubusercontent.com/assets/400285/14705490/22793ddc-07ba-11e6-956e-1a63b01af51a.png)

**Comment by kenmoore** [comment] 2016-04-21 14:49
Hi David, thanks for the report.  I just tried with 3.7.1 and can't reproduce this issue.  Would you mind posting your demo Sketch file here so I can try it?  Maybe there's something unique you're doing which I didn't do in my test.

**Comment by rodnem** [comment] 2016-05-06 11:35
I have got the same trouble on 3.7.2
Sometimes it works, sometimes it doesn't
here is a movie : http://cl.ly/0J1f2c0X2D1c
here is my file : http://cl.ly/2Q1O2o2u2Q1o

**Comment by kenmoore** [comment] 2016-05-19 23:58
@davidvb @rodnem I've just updated the plugin replacing a few deprecated APIs and it's now working for me, but I can't take credit for the fix -- I'm 99% sure whatever was causing the original issue was fixed in Sketch 3.8.1.  If you still notice issues with the latest version please let me know!

Thanks,
Ken

**Closed as completed by kenmoore** 2016-05-19 23:58 UTC
