### ISSUE TITLE
Doesn't work on Sketch 39

### ISSUE THREAD

**Issue by donbailon** [kenmoore/sketch-relabel-button#15] opened 2016-07-22 08:22 UTC
Hello, I try to use the plugin in the new version of Sketch (39) and the plugin doesn't works...

This plugin is very useful, please can you check this?

Thanks! 😄

**Comment by kenmoore** [comment] 2016-07-22 15:02
Hi Alex, you're the 3rd person to report that the plugin isn't working with 39, so I'd like your help troubleshooting -- both of the others were able to get it working by uninstalling and reinstalling the plugin which makes me think they must've been stuck on an older version.  Could you go into your plugins folder and navigate to Button > Relabel Button.sketchplugin, open it in an editor and tell me what the version is?  The latest version is 0.7.... if your plugin IS version 0.7 then please attach the file to this bug so I can do a close comparison with the current to see if there are any differences at all.  Either way, after that you can go ahead and reinstall to fix your issue and I'll contact the folks at Bohemian Coding to tell them what we've found.  Thank you!

**Comment by donbailon** [comment] 2016-07-22 15:32
Hi Ken,

Thanks for reply fast!

I have the v0.5 of the plugin.

I go to install the latest version of the plugin.

Thanks for all and this is a very good plugin men!

Alex.

Alex Bailon
UI Designer
608 865 526tel:608%20865%20526
Twitterhttps://twitter.com/Alex_Bailon

InfoJobs | SCHIBSTED MEDIA GROUP

Best Workplaces 2013http://orientacion-laboral.infojobs.net/contratos-infojobs-2013
406.262 alegrías :)http://www.greatplacetowork.es/mejores-empresas/las-mejores-empresas-para-trabajar-en-espana/641-2012
RESPETEMOS EL MEDIO AMBIENTE: ¿Necesitas realmente imprimir este mail?
CONFIDENCIALIDAD: Este mail es confidencial y para uso exclusivo de su destinatario.

De: Ken Moore notifications@github.com
Responder a: kenmoore/sketch-relabel-button reply@reply.github.com
Fecha: viernes, 22 de julio de 2016, 17:02
Para: kenmoore/sketch-relabel-button sketch-relabel-button@noreply.github.com
CC: Alex Bailon alex.bailon@infojobs.net, Author author@noreply.github.com
Asunto: Re: [kenmoore/sketch-relabel-button] Doesn't work on Sketch 39 (#15)

Hi Alex, you're the 3rd person to report that the plugin isn't working with 39, so I'd like your help troubleshooting -- both of the others were able to get it working by uninstalling and reinstalling the plugin which makes me think they must've been stuck on an older version. Could you go into your plugins folder and navigate to Button > Relabel Button.sketchplugin, open it in an editor and tell me what the version is? The latest version is 0.7.... if your plugin IS version 0.7 then please attach the file to this bug so I can do a close comparison with the current to see if there are any differences at all. Either way, after that you can go ahead and reinstall to fix your issue and I'll contact the folks at Bohemian Coding to tell them what we've found. Thank you!

**Comment by kenmoore** [comment] 2016-07-22 16:01
OK Alex -- I've forwarded the report to Bohemian, hopefully they can fix whatever the issue is.  I'll close this issue for now, thanks for the report!

**Closed as completed by kenmoore** 2016-07-22 16:01 UTC
